all:default
EXAMPLE = sys
LIBS = $(DISTDIR)/$(LIBSKYNAME).a  $(OSLIBS) $(QPIDLIBS)
include $(EXAM_CONFIG_FILE)
default:$(EXEPATH)/test_mutex.exe $(EXEPATH)/test_thread.exe $(EXEPATH)/test_threadpool.exe $(EXEPATH)/test_network.exe