/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileFtpForm.java
 *
 * Created on 2012-6-25, 15:42:51
 */

package com.test.ftp;
import com.test.ftp.ResInfo.ResKey;
import javax.swing.JFileChooser;
import java.io.File;
import java.util.HashMap;
import java.util.Timer;
/**
 *
 * @author qilzh
 */
public class FileFtpForm extends javax.swing.JApplet {
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfFilePath = new javax.swing.JTextField();
        jbtnBrowse = new javax.swing.JButton();
        jlbSelectFile = new javax.swing.JLabel();
        jlbName = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jlbType = new javax.swing.JLabel();
        jcbType = new javax.swing.JComboBox();
        jlbBus = new javax.swing.JLabel();
        jcbBus = new javax.swing.JComboBox();
        jlbArch = new javax.swing.JLabel();
        jcbArch = new javax.swing.JComboBox();
        jlbDescription = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDesc = new javax.swing.JTextArea();
        jPbProcess = new javax.swing.JProgressBar();
        jbtnUpload = new javax.swing.JButton();
        jbtnClearResult = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaResult = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jlbType1 = new javax.swing.JLabel();
        jcbOSType = new javax.swing.JComboBox();
        jcbContainerFormat = new javax.swing.JComboBox();
        jlbContainerFormat = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("*");

        jtfFilePath.setEditable(false);

        jbtnBrowse.setText("浏览...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });

        jlbSelectFile.setText("文件选择");

        jlbName.setText("名称");

        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("*");

        jlbType.setText("类型");

        jcbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "machine", "datablock", "cdrom" }));
        jcbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTypeActionPerformed(evt);
            }
        });

        jlbBus.setText("总线");

        jcbBus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ide", "scsi" }));

        jlbArch.setText("体系结构");

        jcbArch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "x86_64", "i386" }));
        jcbArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbArchActionPerformed(evt);
            }
        });

        jlbDescription.setText("描述");

        jtaDesc.setColumns(20);
        jtaDesc.setRows(5);
        jScrollPane2.setViewportView(jtaDesc);

        jPbProcess.setForeground(new java.awt.Color(51, 255, 0));
        jPbProcess.setToolTipText("");

        jbtnUpload.setText("上传");
        jbtnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUploadActionPerformed(evt);
            }
        });

        jbtnClearResult.setText("清除");
        jbtnClearResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearResultActionPerformed(evt);
            }
        });

        jtaResult.setColumns(20);
        jtaResult.setEditable(false);
        jtaResult.setRows(5);
        jScrollPane1.setViewportView(jtaResult);

        jlbType1.setText("操作系统");

        jcbOSType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Windows 98", "Windows 2000", "Windows XP", "Windows 7", "Windows 8", "Windows 2012", "Windows.NT", "Ubuntu", "Fedora", "CentOS", "SUSE", "redhat", "debian", "Solaris", "FreeBSD", "OpenBSD", "Mac OS", "CGEL", "CGSL" }));
        jcbOSType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOSTypeActionPerformed(evt);
            }
        });

        jcbContainerFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbContainerFormatActionPerformed(evt);
            }
        });

        jlbContainerFormat.setText("容器格式");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jlbSelectFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlbDescription)
                                    .addComponent(jlbName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfFilePath, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jlbType1)
                                            .addGap(32, 32, 32)
                                            .addComponent(jcbOSType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jlbContainerFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jcbContainerFormat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jlbType)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jcbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jlbBus)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jcbBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jlbArch)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbArch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jbtnBrowse))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPbProcess, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                                .addGap(8, 8, 8)
                                .addComponent(jbtnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(461, 461, 461)
                        .addComponent(jbtnClearResult, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSelectFile)
                    .addComponent(jbtnBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jlbName)
                    .addComponent(jlbType)
                    .addComponent(jlbBus)
                    .addComponent(jcbBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbArch)
                    .addComponent(jcbArch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbType1)
                    .addComponent(jcbOSType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbContainerFormat)
                    .addComponent(jcbContainerFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbDescription, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnUpload)
                    .addComponent(jPbProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnClearResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(2780, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1363, 1363, 1363)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnClearResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearResultActionPerformed
        // TODO add your handling code here:
        this.jtaResult.setText("");
}//GEN-LAST:event_jbtnClearResultActionPerformed

    private void jbtnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUploadActionPerformed
        // TODO add your handling code here:
        String file = this.jtfFilePath.getText();
        String name = this.jtfName.getText();
        ResInfo resinfo = new ResInfo(strLang);
        if(name.equals("")){
            AppendResult(resinfo.GetResInfo(ResKey.name_null),false);
            return;
        }
        for(int i = 0;i < name.length();i++){
            if((name.charAt(i) >= 'a' && name.charAt(i) <= 'z') ||
                    (name.charAt(i) >= 'A' && name.charAt(i) <= 'Z') ||
                    (name.charAt(i) >= '0' && name.charAt(i) <= '9') ||
                    (name.charAt(i) == '_') || (name.charAt(i) == '-')){
            } else{
                AppendResult(resinfo.GetResInfo(ResKey.name_input_error),false);
                return;
            }
        }
        if(this.jtfName.getText().length() > 255){
            AppendResult(resinfo.GetResInfo(ResKey.name_length_error),false);
            return;
        }
        if(this.jtaDesc.getText().length() > 128){
            AppendResult(resinfo.GetResInfo(ResKey.desc_length_error),false);
            return;
        }
        for(int i = 0;i<file.length();i++){
            if(file.charAt(i) == 32 ){
                AppendResult(resinfo.GetResInfo(ResKey.name_input_error),false);
                return;
            }
        }
        if(file.equals("")){
            AppendResult(resinfo.GetResInfo(ResKey.must_select_file),false);
            return;
        }
        File fileIn = new File(file);
        if (fileIn.exists()) {
            SetPbProcess(0);
            try{
                UpLoadThread tUploadTh = new UpLoadThread(strHost,strPort,strUser,strPwd,strLang,fileIn,this);
                SetUploadIsEnabled(false);
                tUploadTh.start();
            } catch (Exception e1) {
                System.out.println("上传文件失败:" + e1.getMessage());
            }
        } else {
            AppendResult(resinfo.GetResInfo(ResKey.File_Exits),false);
        }
}//GEN-LAST:event_jbtnUploadActionPerformed

    private void jcbArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbArchActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jcbArchActionPerformed

    private void jcbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTypeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jcbTypeActionPerformed

    private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser jfChooser = new JFileChooser("D:\\..\\..");
        ResInfo resinfo = new ResInfo(strLang);
        String strOpenFile = resinfo.GetResInfo(ResKey.open_file);
        jfChooser.setDialogTitle(strOpenFile);
        int result = jfChooser.showOpenDialog(jFrame1);
        if (result == JFileChooser.APPROVE_OPTION) { // 确认打开
            File fileIn = jfChooser.getSelectedFile();
            if (fileIn.exists()) {
                this.jtfFilePath.setText(fileIn.getPath());
                String filename = fileIn.getName();
                int split = filename.indexOf(".");
                if(split > 0){
                    this.jtfName.setText(filename.substring(0,filename.indexOf(".")).trim());
                } else{
                    this.jtfName.setText(filename);
                }
            } else {
            }
        }else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("Cancel button is pushed.");
        } else if (result == JFileChooser.ERROR_OPTION) {
            System.err.println("Error when select file.");
        }
}//GEN-LAST:event_jbtnBrowseActionPerformed

    private void jcbOSTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOSTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbOSTypeActionPerformed

    private void jcbContainerFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbContainerFormatActionPerformed
        // TODO add your handling code here:
        if(this.jcbContainerFormat.getSelectedIndex() > 0){
            this.jcbType.setEnabled(false);
            this.jcbBus.setEnabled(false);
            this.jcbArch.setEnabled(false);         
            this.jcbOSType.setEnabled(false);
        }
        else{
            this.jcbType.setEnabled(true);
            this.jcbBus.setEnabled(true);
            this.jcbArch.setEnabled(true);
            this.jcbOSType.setEnabled(true);
        }
    }//GEN-LAST:event_jcbContainerFormatActionPerformed

    private String strHost;
    private String strUser;
    private String strPwd;
    private String strPort;
    private String strSession;
    private String strLang;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jPbProcess;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnClearResult;
    private javax.swing.JButton jbtnUpload;
    private javax.swing.JComboBox jcbArch;
    private javax.swing.JComboBox jcbBus;
    private javax.swing.JComboBox jcbContainerFormat;
    private javax.swing.JComboBox jcbOSType;
    private javax.swing.JComboBox jcbType;
    private javax.swing.JLabel jlbArch;
    private javax.swing.JLabel jlbBus;
    private javax.swing.JLabel jlbContainerFormat;
    private javax.swing.JLabel jlbDescription;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbSelectFile;
    private javax.swing.JLabel jlbType;
    private javax.swing.JLabel jlbType1;
    private javax.swing.JTextArea jtaDesc;
    private javax.swing.JTextArea jtaResult;
    private javax.swing.JTextField jtfFilePath;
    private javax.swing.JTextField jtfName;
    // End of variables declaration//GEN-END:variables

    /** Initializes the applet FileFtpForm */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
            this.setSize(java.awt.Toolkit.getDefaultToolkit().getScreenSize().width,java.awt.Toolkit.getDefaultToolkit().getScreenSize().height);
            jPbProcess.setMinimum(0);
            jPbProcess.setMaximum(100);
            strHost = this.getParameter("Host") == null?"10.43.179.132":this.getParameter("Host");
            strUser = this.getParameter("User") == null?"admin":this.getParameter("User");
            strPwd  = this.getParameter("Password") == null?"admin":this.getParameter("Password");
            strPort = this.getParameter("Port") == null?"21":this.getParameter("Port");
            strLang = this.getParameter("Lang") == null?"ch":this.getParameter("Lang");
            strSession = this.getParameter("Password") == null?"4e60df90-dcc5-4499-a0f3-aa4adf8e7884":this.getParameter("Password");
            jPbProcess.setStringPainted(true);
            ResInfo resinfo = new ResInfo(strLang);
            this.jlbName.setText(resinfo.GetResInfo(ResKey.name));
            this.jlbType.setText(resinfo.GetResInfo(ResKey.type));
            this.jlbContainerFormat.setText(resinfo.GetResInfo(ResKey.containerformat));
            this.jlbBus.setText(resinfo.GetResInfo(ResKey.bus));
            this.jlbArch.setText(resinfo.GetResInfo(ResKey.arch));
            this.jlbDescription.setText(resinfo.GetResInfo(ResKey.description));
            this.jlbSelectFile.setText(resinfo.GetResInfo(ResKey.select_file));
            this.jbtnBrowse.setText(resinfo.GetResInfo(ResKey.browse));
            this.jbtnUpload.setText(resinfo.GetResInfo(ResKey.upload));
            this.jbtnClearResult.setText(resinfo.GetResInfo(ResKey.clear));
            if(strLang.compareTo("ch") == 0){
                this.jcbContainerFormat.addItem("无格式");
                this.jcbContainerFormat.addItem("工程镜像");
            }
            else{
                this.jcbContainerFormat.addItem("no format");
                this.jcbContainerFormat.addItem("tpi");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void AppendResult(String value,boolean result){
        this.jtaResult.append(value+"\n");
    }

    public void SetPbProcess(int value){
        this.jPbProcess.setValue(value);
        this.jPbProcess.update(jPbProcess.getGraphics());
    }

    public int GetPbProcess(){
        return this.jPbProcess.getValue();
    }

    public void SetImageInfoTimer(File fileIn){
        Timer timer = new Timer();
        timer.schedule(new ImageInfo(timer,fileIn,strHost,strSession,strLang,GetSetImageParam(),this), 1000, 2000);
    }

    public void SetUploadIsEnabled(boolean benabeled){
        if(this.jcbContainerFormat.getSelectedIndex() > 0)
	{
            this.jcbType.setEnabled(false);
            this.jcbBus.setEnabled(false);
            this.jcbArch.setEnabled(false);
            this.jcbOSType.setEnabled(false);
        }
	else{
		this.jbtnBrowse.setEnabled(benabeled);
		this.jtfName.setEnabled(benabeled);
		this.jcbType.setEnabled(benabeled);
		this.jcbBus.setEnabled(benabeled);
		this.jcbArch.setEnabled(benabeled);
		this.jtaDesc.setEnabled(benabeled);
		this.jbtnUpload.setEnabled(benabeled);
		this.jcbOSType.setEnabled(benabeled);
		this.jcbContainerFormat.setEnabled(benabeled);
	}
    }

    private HashMap GetSetImageParam(){
        HashMap result = new HashMap();
        String containerformat = "";
        String type = "";
        String bus = "";
        String arch = "";
        String description = "";
        String osType = "";
        if(this.jcbContainerFormat.getSelectedIndex() > 0)
        {
            containerformat = "tpi";
        }
        else
        {
            type = this.jcbType.getSelectedItem().toString();
        }
        result.put("name", this.jtfName.getText());
        result.put("type", this.jcbType.getSelectedItem().toString());
        result.put("bus", this.jcbBus.getSelectedItem().toString());
        result.put("arch", this.jcbArch.getSelectedItem().toString());
        result.put("description", this.jtaDesc.getText());
        result.put("os_type",this.jcbOSType.getSelectedItem().toString());
        result.put("container_format", containerformat);
        return result;
    }
}
