all:default
EXAMPLE = misc
LIBS = $(DISTDIR)/$(LIBSKYNAME).a  $(OSLIBS) $(QPIDLIBS)
include $(EXAM_CONFIG_FILE)
default:$(EXEPATH)/test_option_parser.exe $(EXEPATH)/test_ini_parser.exe  $(EXEPATH)/test_algorithm.exe $(EXEPATH)/test_misc.exe 