#include $(_TECS_MAK_PATH)/compileoption.mak
#include ./makeconfig

include $(_NETWORK_VNA_MAIN_MAKEFILE)
include $(_NETWORK_VNA_PUB_MAKEFILE)
include $(_NETWORK_VNA_AGENT_MAKEFILE)
include $(_NETWORK_VNA_HEART_MAKEFILE)
include $(_NETWORK_VNA_ENTRY_MAKEFILE)
include $(_NETWORK_VNA_SWITCH_MAKEFILE)
include $(_NETWORK_VNA_PORT_MAKEFILE)
include $(_NETWORK_VNA_MON_MAKEFILE)
include $(_NETWORK_VNA_VM_MAKEFILE)
include $(_NETWORK_VNA_VXLAN_MAKEFILE)

                 