#include $(_TECS_MAK_PATH)/compileoption.mak
#include ./makeconfig

include $(_NETWORK_WDG_MAIN_MAKEFILE)
include $(_NETWORK_WDG_PUB_MAKEFILE)
#include $(_NETWORK_VNA_AGENT_MAKEFILE)
#include $(_NETWORK_VNA_HEART_MAKEFILE)
include $(_NETWORK_WDG_ENTRY_MAKEFILE)
#include $(_NETWORK_VNA_SWITCH_MAKEFILE)
#include $(_NETWORK_VNA_PORT_MAKEFILE)
#include $(_NETWORK_VNA_MON_MAKEFILE)

                 