all:default
EXAMPLE = timer
LIBS = $(DISTDIR)/$(LIBSKYNAME).a  $(OSLIBS) $(QPIDLIBS)
include $(EXAM_CONFIG_FILE)
default:$(EXEPATH)/test_timer.exe $(EXEPATH)/test_clock.exe $(EXEPATH)/test_datetime.exe