all:default
EXAMPLE = message
LIBS = $(DISTDIR)/$(LIBSKYNAME).a  $(OSLIBS)  $(QPIDLIBS) 
include $(EXAM_CONFIG_FILE)
default:$(EXEPATH)/test_mq.exe $(EXEPATH)/test_mu.exe $(EXEPATH)/test_mu_client.exe $(EXEPATH)/test_mu_server.exe $(EXEPATH)/test_uds.exe
