#!/bin/bash
#
# openais		Script to start and stop the openais_aisexec daemon.
# chkconfig: 2345 97 01
# description: Starts and stops the openais daemon.
# processname: aisexec
# pidfile: /var/run/aisexec.pid
#

# Sanity checks.
if [ -f /usr/local/bin/aisexec ] ; then
  echo 
else
  echo "not exist /usr/local/bin/aisexec .."
  exit 1
fi

[ -x /usr/local/bin/aisexec ] || exit 0

# Source function library.
if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
else
  exit 1
fi

SERVICE=openais
PROCESS=aisexec


OPENAISOPTIONS=


if [ -f /etc/sysconfig/openais ]; then
   . /etc/sysconfig/openais
fi

RETVAL=0

start() {
    cd /usr/local/bin/
    ./keygen
    echo -n $"Starting $SERVICE daemon: "
    ./aisexec
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$SERVICE
}

stop() {
    echo -n $"Stopping $SERVICE daemon: "

    killproc $PROCESS
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        rm -f /var/lock/subsys/$SERVICE
    fi
}

restart() {
    stop
    start
}

reload() {
    echo -n $"Reloading $SERVICE configuration: "

    killproc $PROCESS -HUP
    RETVAL=$?
    echo
    return $RETVAL
}

# See how we were called.
case "$1" in
    start|stop|restart|reload)
        $1
        ;;
    status)
        status $PROCESS
        RETVAL=$?
        ;;
    force-reload)
        reload
	;;
    condrestart|try-restart)
        [ -f /var/lock/subsys/$SERVICE ] && restart || :
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
	exit 1
        ;;
esac
exit $RETVAL
