#!/bin/bash
#
# tecs-hc		Script to start and stop the tecs-hc daemons.
#
# Author:       zhang wenjian <zhang.wenjian2@zte.com.cn>
#
# chkconfig: 2345 99 00
# description: Starts and stops the tecs-hc daemons.
### BEGIN INIT INFO
# Provides: ZTE
# Should-Start: 
# Default-Start: 3 4 5
# Short-Description: Start/stop tecs-hc daemons
# Description: Starts and stops the tecs-hc daemons.
### END INIT INFO

# processname: 
# pidfile: 
#

# Sanity checks.
HC_CONFIG_FILE=/etc/tecs/hc.config
if [ ! -e $HC_CONFIG_FILE ] ; then
  echo "$HC_CONFIG_FILE not exist!"
  exit 1
fi

# Source function library.
if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
else
  exit 1
fi

if [ -f /etc/sysconfig/tecs-hc ]; then
   . /etc/sysconfig/tecs-hc
fi

RETVAL=0
SERVICE=tecs-hc

generate_ssh_key() {
    local private_key_file=~/.ssh/id_dsa
    local public_key_file=~/.ssh/id_dsa.pub
    #ssh私钥或公钥有一个不存在就要重新产生一对
    if [ ! -e $private_key_file ] || [ ! -e $public_key_file ]; then
        rm -rf $public_key_file
        rm -rf $private_key_file
        ssh-keygen -t dsa -f $private_key_file -q -P '' -b 1024
        [ $? == 0 ] && echo "ssh-keygen -t dsa succssfully!"
    fi
}

############################################################################
# 增加service脚本必读！！！
# tecs service prepare函数中调用的脚本或函数必须遵守下面的规范：
# 1. 可以频繁快速重复运行，因为guard要周期性地通过service xxx start来保证服务可用性！
# 2. 每做一个准备动作之前，都要首先判断已经成功准备过了，不要重复劳动，要快进快出！
# 3. 脚本中不能有交互性动作！！！ 如果准备失败了，需要返回约定好的错误码给guard:
#     exit 150 : 本次服务启动失败，需要把整个物理机重启才行
# 4. 宝贵的失败信息需要用logger命令记录到系统日志以备后用，例如: logger "prepare disk failed!!!"
# 5. 如果准备动作比较多，请写成独立的脚本放在/opt/tecs/xx/scripts/目录下，在这里调用即可
# 6. 独立脚本中的代码也要遵守上述1~4条规范。
############################################################################
prepare() {
    echo "$SERVICE is starting ..."
    generate_ssh_key
    #请在这里调用服务启动前的准备动作脚本
    local hung_task_timeout_secs=/proc/sys/kernel/hung_task_timeout_secs
    [ -e $hung_task_timeout_secs ] && echo 0 > $hung_task_timeout_secs 
}

start() {
    [ -x /etc/init.d/iscsid ] && /etc/init.d/iscsid  force-start
    local base line process 
    prepare
    RETVAL=$?
    [ 0 != $RETVAL ] && exit $RETVAL
    
    #下面这句是启动模拟器的脚本，如果是包含模拟器的虚拟机，就会被起起来，错误打印忽略，正式环境执行失败
    run_vm_simulate.sh &>/dev/null

    while read line
    do
        [ "${line:0:1}" == "#" ] && continue
        process=`echo $line |  awk -F' ' '{print $1}'`
        [ -z "$process" ] && continue
        [ `echo "$line" | grep -c -w '\-d'` == "0" ] && line="$line -d"
        base=${process##*/}
        echo -n "Starting $base: "
        daemon $line
        RETVAL=$?
        echo
    done < $HC_CONFIG_FILE
    
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$SERVICE
}

stop() {
    local base line process
    while read line
    do
        [ "${line:0:1}" == "#" ] && continue
        process=`echo $line |  awk -F' ' '{print $1}'`
        [ -z "$process" ] && continue
        base=${process##*/}
        echo -n "Stopping $base: "
        killproc $base
        echo
    done < $HC_CONFIG_FILE
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$SERVICE
}

_status() {
    local base line process
    while read line
    do
        [ "${line:0:1}" == "#" ] && continue
        process=`echo $line |  awk -F' ' '{print $1}'`
        [ -z "$process" ] && continue
        base=${process##*/}
        status $base
    done < $HC_CONFIG_FILE
}

restart() {
    stop
    start
}

# See how we were called.
case "$1" in
    start|stop|restart)
        $1
        ;;
    status)
        _status
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
	exit 1
        ;;
esac
exit $RETVAL
