[
  { "id":"46080",
    "name_ch":"NFS服务启动失败",
    "name_en":"NFS service start failed",
    "reason_ch":"1)NFS服务器没有运行相关NFS服务; 2)权限不足;",
    "reason_en":"1)NFS Server is not running; 2)permission denied.",
    "op_ch":"1)检查NFS服务器上NFSD、MOUNTD、PORTMAP、是否运行正常; 2)检查NFS服务器上共享的文件目录是否有相应的权限;",
    "op_en":"1)Check the nfsd、mountd、portmap of the nfs server; 2)check the /etc/exports of the nfs server."},

  { "id":"46081",
    "name_ch":"TC文件存储数据库初始化失败",
    "name_en":"TC file storage db init failed",
    "reason_ch":"postgresql 数据库没有运行;",
    "reason_en":"postgresql is not running.",
    "op_ch":"用 initdb -D /usr/local/pgsql/data ; pg_ctl -D /usr/local/pgsql/data start 命令重新启动数据库;",
    "op_en":"Restart db use command: initdb -D /usr/local/pgsql/data ; pg_ctl -D /usr/local/pgsql/data start."},

  { "id":"46082",
    "name_ch":"CC文件存储数据库初始化失败",
    "name_en":"CC file storage db init failed",
    "reason_ch":"postgresql 数据库没有运行;",
    "reason_en":"postgresql is not running.",
    "op_ch":"用 initdb -D /usr/local/pgsql/data; pg_ctl -D /usr/local/pgsql/data start 命令重新启动数据库;",
    "op_en":"Restart db use command: initdb -D /usr/local/pgsql/data; pg_ctl -D /usr/local/pgsql/data start."},

  { "id":"46083",
    "name_ch":"数据库记录插入失败",
    "name_en":"Insert db record failed",
    "reason_ch":"插入数据库记录失败;",
    "reason_en":"Insert db record failed.",
    "op_ch":"检查数据库日志信息进行定位;",
    "op_en":"Check the insert db record log."},

  { "id":"46084",
    "name_ch":"下载文件失败",
    "name_en":"Download file failed",
    "reason_ch":"通过NFS拷贝文件失败;",
    "reason_en":"Copy the file by NSF service failed.",
    "op_ch":"1)检查相应的NFS服务是否运行正常; 2)空间是否足够?",
    "op_en":"1)check the NFS service; 2)is there enough space?"},

  { "id":"46085",
    "name_ch":"NFS 挂载失败",
    "name_en":"NFS mount failed",
    "reason_ch":"1)NFS 服务器没有运行; 2)权限是否正确;",
    "reason_en":"1)NFS Server is not running;  2)permission denied.",
    "op_ch":"1)检查NFS服务器上NFSD、MOUNTD、PORTMAP是否运行正常; 2)检查NFS服务器上共享的文件目录是否有相应的权限;",
    "op_en":"1)check the NFS service; 2)permission denied."},

  { "id":"46096",
    "name_ch":"集群离线",
    "name_en":"cluster off-line",
    "reason_ch":"1)消息服务器故障; 2)集群掉电或故障;",
    "reason_en":"1)Message Broker fault; 2)Cluster poweroff or fault.",
    "op_ch":"1)检查对应集群是否运行正常; 2)检查消息服务器是否运行正常;",
    "op_en":"1)check cluster run state; 2)check message broker run state."},

  { "id":"46097",
    "name_ch":"集群重名",
    "name_en":"Duplication of cluster name",
    "reason_ch":"集群名配置重复;",
    "reason_en":"Name of cluster duplicated.",
    "op_ch":"检查集群名字是否配置为相同;",
    "op_en":"Check if clusters have same name."},
  
  { "id":"46112",
    "name_ch":"主机离线",
    "name_en":"Host off-line",
    "reason_ch":"1)主机重启或关机; 2)主机与CC通信断;",
    "reason_en":"1)host is reboot or shutdown; 2)communication is broken between host with cluster controller.",
    "op_ch":"1.检查主机是否运行,如果没有,则使其上电运行,观察告警是否恢复; 2.检查主机与CC的连接,使其连接正常,观察告警是否恢复;",
    "op_en":"1.check host run state; 2.check message broker run state."},

  { "id":"46114",
    "name_ch":"主机内存故障",
    "name_en":"Host memory error",
    "reason_ch":"主机内存故障;",
    "reason_en":"memory is error.",
    "op_ch":"1)重新拔插内存条或更换新的内存条重新上电,若告警恢复,结束告警处理,否则转2; 2)更换单板,重新上电,查看告警是否恢复,Y-> 告警恢复,结束告警处理. N->告警未恢复,转3; 3)联系中兴通讯;",
    "op_en":"1)remove and plug the memory or replace the memory by a new one and  power on the board, then check if the alarm restored. Y-> The troubleshooting completes.  N-> go to 2;  2)Replace the faulty board by a new one and power one the board to check if  the alarm restored. Y-> The troubleshooting completes. N-> go to 3; 3)Make records of the alarm information and contact ZTE Cooperation."},

  { "id":"46115",
    "name_ch":"主机硬盘故障",
    "name_en":"Host hard disk error",
    "reason_ch":"主机硬盘故障;",
    "reason_en":"hard disk is error.",
    "op_ch":"1)按照部件更换指导，更换硬盘，查看告警是否恢复; 是->结束, 否->2; 2)请联系中兴通讯;",
    "op_en":"1)Change another good harddisk acording to the suggestion, check whether the alarm is clear; Y: End; N: go to 2; 2)Please contact ZTE."},

  { "id":"46116",
    "name_ch":"主机晶振故障",
    "name_en":"Host oscillator error",
    "reason_ch":"晶振停振或产生频偏;",
    "reason_en":"Oscillator may stop oscillating or meet frequency deviation.",
    "op_ch":"更换单板;",
    "op_en":"Replace the board."},

  { "id":"46117",
    "name_ch":"端口速率与设置不符",
    "name_en":"The speed mode of the port doesn't match with settings",
    "reason_ch":"因本端芯片性能或对端未成功设置,外部端口工作模式设置没有生效,端口没有在设置的速率工作;",
    "reason_en":"The speed mode settings of the external port does not take effect due to faulty performance of the chip on the local end or unsuccessful settings on the peer end.",
    "op_ch":"1)检查对接两端速率设置是否一致并正确; 2)联系中兴通讯;",
    "op_en":"1)Check the speed settings on the both end if it is correct and consistent; 2)Please contact ZTE Corporation."},

  { "id":"46118",
    "name_ch":"端口双工与设置不符",
    "name_en":"The duplex mode of the port doesn't match with settings",
    "reason_ch":"因本端芯片性能或对端未成功设置,外部端口工作模式设置没有生效,端口没有在设置的双工工作;",
    "reason_en":"The duplex mode settings of the external port does not take effect due to faulty performance of the chip on the local end or unsuccessful settings on the peer end.",
    "op_ch":"1)检查对接两端双工模式设置是否一致并正确. Y->转2; N->修改两端双工模式设置确保正确并一致,观察告警是否消失. Y->结束; N->转2; 2)联系中兴通讯;",
    "op_en":"1)Check the duplex mode settings on the both end if it is correct and consistent.  Y->Go to 2. N->Modify the duplex mode settings on the both end to make it correlct and consistent with each other, and then check the alarm if it is eliminated. Y->End. N->Go to 2; 2)Please contact ZTE Corporation."},

  { "id":"46119",
    "name_ch":"以太网口down",
    "name_en":"Ethernet port is down",
    "reason_ch":"1)以太网口链接断开; 2)以太网口硬件故障;",
    "reason_en":"Ethernet port is down.",
    "op_ch":"1)检查链路是否正常; 2)检查端口模式配置是否合理;",
    "op_en":"1)Check link status if it is up; 2)Check mode settings of the port if it is reasonable."},

  { "id":"46120",
    "name_ch":"TRUNK端口down",
    "name_en":"Trunk port is down",
    "reason_ch":"Trunk链路断开;",
    "reason_en":"Trunk port is down.",
    "op_ch":"检查组成turnk口的各物理端口链路是否正常;",
    "op_en":"check link status if it is up."},

  { "id":"46121",
    "name_ch":"以太网口未被连接",
    "name_en":"Ethernet port is not linked",
    "reason_ch":"1)以太网口线缆没有正确连接; 2)以太网口硬件故障; 3)配置错误,导致无法检测到连接;",
    "reason_en":"1)The Port has none connected; 2)The port har hard error; 3)The config of port is error.",
    "op_ch":"1)检查连线是否正常; 2)更换设备; 3)检查配置;",
    "op_en":"1)check the cable of the port is correct assemble; 2)replace the board."},

 { "id":"46123",
    "name_ch":"主机硬盘可用存储不足",
    "name_en":"The free hard disk of host is not enough.",
    "reason_ch":"主机硬盘故障;",
    "reason_en":"Hard disk of host is error.",
    "op_ch":"1)检测主机硬盘是否故障; 2)更换硬盘或刀片; 3）检测配置",
    "op_en":"1)Check wheather the hard disk of host is error. 2)Replace the hard disk or the board. 3)Check the configuration of the host."},

 { "id":"46124",
    "name_ch":"主机可用内存不足",
    "name_en":"The free memory of host is not enough.",
    "reason_ch":"主机内存故障或被拔出;",
    "reason_en":"Hard memory bank of host is error or is pulled out.",
    "op_ch":"1)检测主机内存是否故障; 2)更换内存或刀片; 3）检测配置",
    "op_en":"1)Check wheather the memory bank of host is error. 2)Replace the memory bank or the board. 3)Check the configuration of the host."},

 { "id":"46125",
    "name_ch":"主机可用CPU数目不足",
    "name_en":"The free CPU of host is not enough.",
    "reason_ch":"主机CPU被更换等;",
    "reason_en":"The CPU of host is changed.",
    "op_ch":"1)检测主机CPU; 2)更换刀片; 3）检测配置",
    "op_en":"1)Check the CPU of host. 2)Replace the board. 3)Check the configuration of the host."},

  { "id":"46126",
    "name_ch":"主机硬盘警告",
    "name_en":"Host hard disk warn",
    "reason_ch":"主机硬盘警告",
    "reason_en":"Host hard disk warn",
    "op_ch":"1)使用硬盘修复工具或命令修复, 查看告警是否恢复, 是->结束, 否则->2; 2)请联系中兴通讯;",
    "op_en":"1)Try to fix using disk fix tools or system commands, check whether the alarm is clear; Y: End; N: go to 2; 2)Please contact ZTE."},

  { "id":"46128",
    "name_ch":"DHCP服务启动失败",
    "name_en":"DHCP service start failed",
    "reason_ch":"DHCP配置错误;",
    "reason_en":"DHCP configuration is error.",
    "op_ch":"检查DHCP配置;",
    "op_en":"Check DHCP configuration."},

  { "id":"46129",
    "name_ch":"DHCP没有空闲IP地址",
    "name_en":"DHCP does not has free ip.",
    "reason_ch":"DHCP配置错误;",
    "reason_en":"DHCP configuration is error.",
    "op_ch":"检查DHCP配置;",
    "op_en":"Check DHCP configuration."},

  { "id":"46144",
    "name_ch":"主机网络启动失败",
    "name_en":"Host network start failed",
    "reason_ch":"主机网络配置错误;",
    "reason_en":"Host network configuration is error.",
    "op_ch":"检查主机网络配置",
    "op_en":"Host network configuration."},

  { "id":"46160",
    "name_ch":"存储离线",
    "name_en":"Storage Off-line",
    "reason_ch":"消息服务器故障; 存储掉电故障;",
    "reason_en":"Message Broker fault; Storage poweroff or fault.",
    "op_ch":"检查对应的存储是否运行正常; 检查消息服务器是否正常",
    "op_en":"Check storage run state; Check Message broker run state."},    

  { "id":"46176",
    "name_ch":"虚拟机离线",
    "name_en":"Vm offline",
    "reason_ch":"物理机离线",
    "reason_en":"Host offline",
    "op_ch":"重启HC进程",
    "op_en":"Reboot process HC"},

  { "id":"46177",
    "name_ch":"虚拟机开机失败",
    "name_en":"Start vm failed",
    "reason_ch":"HC进程异常；libvert异常；虚拟机配置镜像不对",
    "reason_en":"Process HC have some exception； Livbert havesome exception；Configuration for machine is wrong",
    "op_ch":"重启HC进程; 重启libvet; 更改虚拟机镜像配置",
    "op_en":"Reboot process HC; Reboot libvert; Change configuration for vm"},

  { "id":"46178",
    "name_ch":"虚拟机物理状态与逻辑状态不符",
    "name_en":"Vm physical state is conflict with logical state",
    "reason_ch":"HC进程异常；Libvert异常；人为干预",
    "reason_en":"Process HC have some exception；Livbert havesome exception；Human intervention",
    "op_ch":"撤销虚拟机，重新部署",
    "op_en":"Cancel the vm, the re-deploy it"}
]