[
        {"id":"0", "des_ch":"成功", "des_en":"OK"},
        {"id":"1", "des_ch":"错误", "des_en":"Error"},
	{"id":"2", "des_ch":"错误,操作失败", "des_en":"Error, operation failed"},
	{"id":"3", "des_ch":"错误,操作超时", "des_en":"Error, operation time out"},
	{"id":"4", "des_ch":"错误,鉴权管理无效", "des_en":"Error, authentication manager is invalid"},
	{"id":"5", "des_ch":"错误,用户鉴权失败", "des_en":"Error, failed to authenticate user"},
	{"id":"6", "des_ch":"错误,用户操作鉴权失败", "des_en":"Error, failed to authorize usr's operation"},
	{"id":"7", "des_ch":"错误,链接数据库失败", "des_en":"Error, falied to connect database"},
	{"id":"8", "des_ch":"错误,插入数据库失败", "des_en":"Error, falied to insert database"},
	{"id":"9", "des_ch":"错误,更新数据库失败", "des_en":"Error, falied to update database"},
	{"id":"10", "des_ch":"错误,删除数据库失败", "des_en":"Error, falied to delete database"},
	{"id":"11", "des_ch":"错误,查询数据库失败", "des_en":"Error, falied to query database"},
        {"id":"12", "des_ch":"错误,数据库未知失败", "des_en":"Error, unknown database fail"},
	{"id":"13", "des_ch":"错误,创建对象失败", "des_en":"Error, failed to allocate object instance"},
	{"id":"14", "des_ch":"错误,删除对象失败", "des_en":"Error, failed to drop object instance"},
	{"id":"15", "des_ch":"错误,获取对象失败", "des_en":"Error, failed to get object instance"},
	{"id":"16", "des_ch":"错误,更新对象失败", "des_en":"Error, failed to update object instance"},
	{"id":"17", "des_ch":"错误,对象不存在", "des_en":"Error, object instance not exist"},
	{"id":"18", "des_ch":"错误,无效参数", "des_en":"Error, invalide parameter"},
        {"id":"19", "des_ch":"错误,操作失败", "des_en":"Error, failed to do action"},
	{"id":"20", "des_ch":"错误,会话无效", "des_en":"Erorr, session is invalid"},
	{"id":"21", "des_ch":"错误,连接数据库失败", "des_en":"Error, falied to connect database"},
	{"id":"22", "des_ch":"错误,无效的License", "des_en":"Error, license is invalid"},
	{"id":"25", "des_ch":"操作进行中", "des_en":"Error, operation is running"},	
	{"id":"27", "des_ch":"错误,当前状态不允许此操作", "des_en":"Error,Current state does not allow this operation"},		
	{"id":"43", "des_ch":"错误,文件名非法", "des_en":"Error, file name is invalid"},
	{"id":"1002", "des_ch":"失败,CC未应答", "des_en":"Failed, Cluster Controller is not answered"},
	{"id":"1003", "des_ch":"错误,集群未注册到TC中", "des_en":"Error, cluster have not registered into the Tecs Center"},
	{"id":"1004", "des_ch":"失败,物理机不存在", "des_en":"Failed, host is not exist"},
	{"id":"1005", "des_ch":"失败,物理机正忙", "des_en":"Failed, host is busy"},
	{"id":"1006", "des_ch":"失败,物理机不是已注销", "des_en":"Failed, host is not unregistered"},
	{"id":"1007", "des_ch":"失败,物理机不是已注册", "des_en":"Failed, host is not registered"},
	{"id":"1008", "des_ch":"失败,物理机上运行有虚拟机", "des_en":"Failed, there are some VMs running on the host"},
	{"id":"1009", "des_ch":"失败,物理机已注册到其他集群", "des_en":"Conflict, host have joined the other cluster"},
	{"id":"1010", "des_ch":"错误,命令为空", "des_en":"Error, command is empty"},
	{"id":"1011", "des_ch":"失败,命令执行失败", "des_en":"Failed, command execute failed"},
	{"id":"1012", "des_ch":"错误,网口名称为空", "des_en":"Error, port name is empty"},
	{"id":"1013", "des_ch":"错误,无效的网口配置参数", "des_en":"Error, invalid port config info"},
	{"id":"1014", "des_ch":"失败,创建网口配置失败", "des_en":"Failed, create a new port config failed"},
	{"id":"1015", "des_ch":"失败,不能停用该网口，因为该物理机上运行有虚拟机", "des_en":"Failed, can not stop the port, because of there are some VMs running on the host"},
	{"id":"1016", "des_ch":"失败,网口不存在", "des_en":"Failed, port is not exist"},
	{"id":"1017", "des_ch":"错误,trunk口名称为空", "des_en":"Error, trunk name is empty"},
	{"id":"1018", "des_ch":"失败,trunk口不存在", "des_en":"Failed, trunk is not exist"},
	{"id":"1019", "des_ch":"失败,组成trunk口的网口SRIOV数目不一致", "des_en":"Failed, sriov number of trunk ports is different."},
	{"id":"1020", "des_ch":"失败,不能修改该trunk口的类型，因为该物理机上运行有虚拟机", "des_en":"Failed, can not modify the trunk type, because of there are some VMs running on the host"},
	{"id":"1021", "des_ch":"失败,不能删除该trunk口，因为该物理机上运行有虚拟机", "des_en":"Failed, can not delete the trunk, because of there are some VMs running on the host"},
	{"id":"1022", "des_ch":"错误,集群属性名称非法", "des_en":"Error, cluster config name is illegal"},
	{"id":"1023", "des_ch":"失败,设置集群属性配置失败", "des_en":"Failed, set cluster config failed"},
	{"id":"1024", "des_ch":"失败,删除集群属性配置失败", "des_en":"Failed, delete cluster config failed"},
	{"id":"1025", "des_ch":"错误,该cpu info id不存在", "des_en":"Error, cpu_info_id is not exist"},
	{"id":"1026", "des_ch":"错误,cpu info和cpu info id字段均有效", "des_en":"Error, cpu_info and cpu_info_id are both valid"},
	{"id":"1027", "des_ch":"失败,设置tcu配置失败", "des_en":"Failed, set tcu config failed"},
	{"id":"1028", "des_ch":"失败,删除tcu配置失败", "des_en":"Failed, delete tcu config failed"},
	{"id":"1029", "des_ch":"失败,cpu已经被虚拟机使用", "des_en":"Failed, cpu is used by vm"},
	{"id":"1030", "des_ch":"失败,物理机不支持这个操作", "des_en":"Failed, the host is not support eht operation"},
	{"id":"1031", "des_ch":"失败,设置默认网络平面失败", "des_en":"Failed, set default netplane config failed"},
	{"id":"1032", "des_ch":"失败,删除默认网络平面失败", "des_en":"Failed, delete default netplane config failed"},
	{"id":"1033", "des_ch":"失败,trunk口已存在，不能重复创建", "des_en":"Failed, trunk is exist and can not create repeat"},
	{"id":"1034", "des_ch":"错误,网络平面名称不能为空", "des_en":"Error, netplane name is empty."},
	{"id":"1035", "des_ch":"错误,网络平面名称已存在", "des_en":"Error, netplane name is exist."},
	{"id":"1036", "des_ch":"错误,网络平面名称不存在", "des_en":"Error, netplane name is not exist."},
	{"id":"1037", "des_ch":"错误,网络平面删除失败,请检查是否已使用.", "des_en":"Error, netplane deleted failed, maybe in used."},
	{"id":"1038", "des_ch":"错误,设置网络平面失败.", "des_en":"Error, netplane set failed."},
	{"id":"1039", "des_ch":"错误,不能设置网络平面,该网络平面已经有虚拟机在使用.", "des_en":"Error, can not set the netplane, because of there are some VMs running on the netplane."},
	{"id":"1040", "des_ch":"错误,不能设置环回,该网口已经加入网络平面.", "des_en":"Error, can not set the loopback mode, because of there are netplane on the port."},
	{"id":"1041", "des_ch":"错误,不能设置环回或网络平面,该网口是bond成员口.", "des_en":"Error, can not set the loopback mode or netplane, because of this port is used by bonding."},
	{"id":"1042", "des_ch":"错误,不能设置环回,该网口不是SRIOV口.", "des_en":"Error, can not set the loopback mode, because of this port is not sriov port."},
	{"id":"1043", "des_ch":"错误,不能设置网络平面,该网口是环回模式且网络平面已经被其它网口使用.", "des_en":"Error, can not set the netplane, because the port is loopback mode port and this netplane is used by other port."},
	{"id":"1044", "des_ch":"错误,不能设置网络平面,该网络平面已经被环回网口使用.", "des_en":"Error, can not set the netplane, because the netplane is used by loopback port."},
	{"id":"1045", "des_ch":"错误,网络平面增加失败.", "des_en":"Error, netplane add failed."},
	{"id":"1046", "des_ch":"错误,成员口为环回模式.", "des_en":"Error, trunk member is loopback mode port."},
        {"id":"1047", "des_ch":"失败, 集群增加CMM失败", "des_en":"Failed, cluster agent add cmm fail."},
        {"id":"1048", "des_ch":"失败, 集群设置CMM失败", "des_en":"Failed, cluster agent set cmm fail."},
        {"id":"1049", "des_ch":"失败, 集群删除CMM失败", "des_en":"Failed, cluster agent delete cmm fail."},
        {"id":"1050", "des_ch":"失败, 集群查询CMM失败", "des_en":"Failed, cluster agent query cmm fail."},	
        {"id":"1051", "des_ch":"失败, 设置TCU失败,因为已经有使用该TCU的虚拟机在运行", "des_en":"Failed, set tcu num config failed because there are some VMs running."},	    
        {"id":"1052", "des_ch":"错误, CMM的IP未设置", "des_en":"Error, not config cmm ip address."},	    
        {"id":"1053", "des_ch":"错误, 操作不支持", "des_en":"Error, operate not support."},	            
        {"id":"1054", "des_ch":"错误, CMM配置错误", "des_en":"Error, cmm configured incorrect."},	            
	{"id":"2001", "des_ch":"错误, 获取数据库接口失败", "des_en":"Error, the netplane get db interface failed."},
	{"id":"2002", "des_ch":"错误, 网络平面不存在", "des_en":"Error, the netplane is not exsit."},
	{"id":"2003", "des_ch":"错误, 网络平面已经存在", "des_en":"Error, the netplane has already exsit."},
	{"id":"2004", "des_ch":"错误, 网络平面参数无效", "des_en":"Error, the netplane para is invalid."},
	{"id":"2005", "des_ch":"错误, 逻辑网络不存在", "des_en":"Error, the logicnet is not exsit."},
	{"id":"2006", "des_ch":"错误, 逻辑网络已存在", "des_en":"Error, the logicnet has alredy exsit."},
	{"id":"2007", "des_ch":"错误, 逻辑网络参数无效", "des_en":"Error, the logicnet para is invalid."},
	{"id":"2008", "des_ch":"错误, IP范围参数无效", "des_en":"Error, the ipv4 range para is invalid."},
	{"id":"2009", "des_ch":"错误, IP范围参数无效", "des_en":"Error, the ipv4 range calc invalid."},
	{"id":"2010", "des_ch":"错误, IP范围不存在", "des_en":"Error, the ipv4 range is not exsit."},
	{"id":"2011", "des_ch":"错误, IP范围不在同一个子网", "des_en":"Error, the ipv4 range is not in same subnet."},
	{"id":"2012", "des_ch":"错误, IP范围无效", "des_en":"Error, the ipv4 range is invalid."},
	{"id":"2013", "des_ch":"错误, IP范围已经被占用", "des_en":"Error, the ipv4 range is occupied."},
	{"id":"2014", "des_ch":"错误, 物理主机名不存在", "des_en":"Error,hostname not exist"},
	{"id":"2015", "des_ch":"错误, MAC范围参数无效", "des_en":"Error, the mac range para is invalid."},
	{"id":"2016", "des_ch":"错误, MAC范围参数无效", "des_en":"Error, the mac range calc invalid."},
	{"id":"2017", "des_ch":"错误, MAC范围不存在", "des_en":"Error, the mac range is not exsit."},
	{"id":"2018", "des_ch":"错误, MAC范围无效", "des_en":"Error, the mac range is invalid."},
	{"id":"2019", "des_ch":"错误, MAC范围oui无效", "des_en":"Error, the mac range oui invalid."},
	{"id":"2020", "des_ch":"错误, MAC解析错误", "des_en":"Error, the mac parse error."},
	{"id":"2021", "des_ch":"错误, MAC范围已经被占用", "des_en":"Error, the mac range is occupied."},
	{"id":"2022", "des_ch":"错误, VLAN范围参数无效", "des_en":"Error, the vlan range para is invalid."},
	{"id":"2023", "des_ch":"错误, VLAN范围参数无效", "des_en":"Error, the vlan range calc error."},
	{"id":"2024", "des_ch":"错误, VLAN范围不存在", "des_en":"Error, the vlan range is not exsit."},
	{"id":"2025", "des_ch":"错误, VLAN范围已经被占用", "des_en":"Error, the vlan range is occupied."},
        {"id":"2026", "des_ch":"错误, SegmentID范围参数无效", "des_en":"Error, the segment range para is invalid."},
        {"id":"2027", "des_ch":"错误, SegmentID范围参数无效", "des_en":"Error, the segment range calc error."},
        {"id":"2028", "des_ch":"错误, SegmentID范围不存在", "des_en":"Error, the segment range is not exsit."},
        {"id":"2029", "des_ch":"错误, SegmentID范围已经被占用", "des_en":"Error, the segment range is occupied."},
	{"id":"2161", "des_ch":"错误, 端口组操作码无效", "des_en":"Error, the portgroup opercode is invalid."},
	{"id":"2162", "des_ch":"错误, 端口组名字为空或无效", "des_en":"Error, the portgroup is empty or invalid."},
	{"id":"2163", "des_ch":"错误, 端口组参数无效", "des_en":"Error, Input the invalid params of portgroup."},
	{"id":"2164", "des_ch":"错误, 获取操作句柄失败", "des_en":"Error, Get the handler fail."},
	{"id":"2165", "des_ch":"错误, 获取端口组VLAN范围失败", "des_en":"Error, Get portgroup's trunk vlanrange fail."},
	{"id":"2166", "des_ch":"错误, 端口组不存在", "des_en":"Error, the portgroup is not exsit."},
	{"id":"2167", "des_ch":"错误, 端口组已存在", "des_en":"Error, the portgroup is exsit already."},
	{"id":"2168", "des_ch":"错误, 端口组在使用中", "des_en":"Error, the portgroup is in using."},
	{"id":"2169", "des_ch":"错误, 数据库操作失败", "des_en":"Error, operator db of portgroup fail."},
    {"id":"2170", "des_ch":"错误, 禁止修改或删除默认端口组", "des_en":"Error, the port group is default, cannot modify or delete."},
    {"id":"2171", "des_ch":"错误, 端口组Access VLAN在网络平面的VLAN范围内", "des_en":"Error, the access vlan is in netplane's vlanrange."},
    {"id":"2172", "des_ch":"错误, Native VLAN不在VLAN范围内", "des_en":"Error, the native vlan is not in trunk's vlanrange."},
    {"id":"2173", "des_ch":"错误, 网络平面的VLAN范围未配置,不能配置网络号", "des_en":"Error, netplane's vlanrange is empty, so cannot config isolate vlan."}, 
    {"id":"2174", "des_ch":"错误, 端口组VLAN范围无效", "des_en":"Error, the port group vlan range is invalid."},
    {"id":"2175", "des_ch":"错误, 端口组VLAN范围已存在", "des_en":"Error, the port group vlan range is exist."},
    {"id":"2176", "des_ch":"错误, 端口组VLAN范围不存在", "des_en":"Error, the port group vlan range is not exist."},
    {"id":"2177", "des_ch":"错误, 操作VLAN范围数据库失败", "des_en":"Error, operator db of trunk's vlanrange fail."},
    {"id":"2178", "des_ch":"错误, VLAN范围合并失败", "des_en":"Error, Combining the calculation of vlanrange fail."},
    {"id":"2179", "des_ch":"错误, VLAN范围与网络平面的VLAN范围或Native VLAN冲突", "des_en":"Error, the trunk's vlanrange is conflict witch netplane's or nativevlan."},
    {"id":"2180", "des_ch":"错误, SegmentID在网络平面的vlan范围内", "des_en":"Error, the segment is in netplane's vlanrange."},
    {"id":"2181", "des_ch":"错误, 网络平面的SegmentID范围为空，不能配置孤立的segmentID", "des_en":"Error, netplane's segmentrange is empty, so cannot config isolate segment."},
    {"id":"2201", "des_ch":"错误, 交换操作码无效", "des_en":"Error, the switch opercode is invalid."},
	{"id":"2202", "des_ch":"错误, 交换获取实例失败", "des_en":"Error, the switch get instance failed."},
	{"id":"2203", "des_ch":"错误, 交换获取管理口实例失败", "des_en":"Error, the switch get portmgr instance failed."},
	{"id":"2204", "des_ch":"错误, 交换获取vswitch数据库实例失败", "des_en":"Error, the switch get vswitch db instance failed."},
	{"id":"2205", "des_ch":"错误, 交换获取数据库句柄失败", "des_en":"Error, the switch get vswitchmap db instance failed."},
	{"id":"2206", "des_ch":"错误, 交换配置和通配发生冲突", "des_en":"Error, the operator of switch is conflict with wildcast's."},
	{"id":"2207", "des_ch":"错误, 交换端口无效", "des_en":"Error, the switch port is invalid."},
	{"id":"2208", "des_ch":"错误, 获取端口组信息失败", "des_en":"Error, the switch get portgroup infomation failed."},
	{"id":"2209", "des_ch":"错误, 交换名称无效", "des_en":"Error, the switch name is invalid."},
	{"id":"2210", "des_ch":"错误, 交换已存在", "des_en":"Error, the switch is already exsit."},
	{"id":"2211", "des_ch":"错误, 交换正在使用中", "des_en":"Error, the switch is using."},
	{"id":"2212", "des_ch":"错误, 交换操作数据库失败", "des_en":"Error, the switch operator db fail."},
	{"id":"2213", "des_ch":"错误, 交换端口操作数据库失败", "des_en":"Error, the switch port operator db fail."},
	{"id":"2214", "des_ch":"错误, 交换删除未完成", "des_en":"Error, the switch delete not finish."},
	{"id":"2215", "des_ch":"错误, 获取端口信息失败", "des_en":"Error, switch get port infomation failed."},
    {"id":"2216", "des_ch":"错误, 交换增加bond口失败", "des_en":"Error, the switch add bond failed."},
    {"id":"2217", "des_ch":"错误, 交换删除bond口失败", "des_en":"Error, the switch del bond failed."},
    {"id":"2218", "des_ch":"错误, 交换删除bond slave失败", "des_en":"Error, the switch del bond slave failed."},
    {"id":"2219", "des_ch":"错误, 交换获取bond slave失败", "des_en":"Error, the switch get bond slave failed."},
    {"id":"2220", "des_ch":"错误, 交换增加网桥失败", "des_en":"Error, the switch add bridge failed."},
    {"id":"2221", "des_ch":"错误, 交换删除网桥失败", "des_en":"Error, the switch del bridge failed."},
    {"id":"2222", "des_ch":"错误, 交换设置属性失败", "des_en":"Error, the switch set attr failed."},
	{"id":"2223", "des_ch":"错误, 交换端口冲突", "des_en":"Error, the switchport is conflict."},
	{"id":"2224", "des_ch":"错误, 交换端口是混用的", "des_en":"Error, the switchport is mixed."},
    {"id":"2225", "des_ch":"错误, 禁止操作管理端口对应的交换", "des_en":"Error, the switch operator kernelDVS fail."},
    {"id":"2226", "des_ch":"错误, 交换查询VNA UUID失败", "des_en":"Error, the switch query vnauuid fail."},
    {"id":"2227", "des_ch":"错误, 交换合并请求信息失败", "des_en":"Error, the switch merge requestinfo fail."},
    {"id":"2228", "des_ch":"错误, 交换获取sriov vf资源失败", "des_en":"Error, the switch get sriov vf resource fail."},
    {"id":"2229", "des_ch":"错误, 交换uplink网口添加失败", "des_en":"Error, add switch's uplink port fail."},
    {"id":"2230", "des_ch":"错误, EVB端口添加失败", "des_en":"Error, add switch's evb port fail."},
    {"id":"2231", "des_ch":"错误, EVB端口删除失败", "des_en":"Error, delete switch's evb port fail."},
    {"id":"2232", "des_ch":"错误, 交换名称重命名失败", "des_en":"Error, rename bridge fail."},
	{"id":"2233", "des_ch":"错误, 参数校验失败", "des_en":"Error, the parameters check fail."},
    {"id":"2234", "des_ch":"错误, 启动检测定时器失败", "des_en":"Error, timer for checking create fail."},
    {"id":"2235", "des_ch":"错误, 获取交换连接的所有主机信息失败", "des_en":"Error, get all hosts in the switch fail."},
    {"id":"2236", "des_ch":"错误, 修改交换属性失败", "des_en":"Error, modify switch attribute fail."},
    {"id":"2237", "des_ch":"错误, VTEP端口添加失败", "des_en":"Error, add vtep port fail."},
    {"id":"2238", "des_ch":"错误, VTEP端口删除失败", "des_en":"Error, delete vtep port fail."},
    {"id":"2239", "des_ch":"错误, 查询VTEP端口信息失败", "des_en":"Error, query vtep port infomation fail."},
    {"id":"2401", "des_ch":"错误, 端口名称无效", "des_en":"Error, input port name is invalid."},
    {"id":"2402", "des_ch":"错误, 端口操作无效", "des_en":"Error, input port operate code is invalid."},
    {"id":"2403", "des_ch":"错误, 端口配置参数无效", "des_en":"Error, input port config parameter is invalid."},
    {"id":"2404", "des_ch":"错误, 端口配置失败", "des_en":"Error, config port failed  in some instances."},
    {"id":"2405", "des_ch":"错误, 端口配置操作数据库失败", "des_en":"Error, operate DB failed for config port."},
    {"id":"2406", "des_ch":"错误, 端口配置通配检查冲突", "des_en":"Error, WC checks failed for config port."},
    {"id":"2407", "des_ch":"错误, 端口配置数据库检查冲突", "des_en":"Error, tDB conflict checks failed for config port."},
    {"id":"2060", "des_ch":"错误, vnet库没有正常工作", "des_en":"Error, the vnet lib is not working."},
	{"id":"2061", "des_ch":"错误, 通配交换操作码无效", "des_en":"Error, the wildcard switch opercode is invalid."},
	{"id":"2062", "des_ch":"错误, 通配交换获取实例失败", "des_en":"Error, the wildcard switch get instance failed."},
    {"id":"2063", "des_ch":"错误, 通配交换名称为空", "des_en":"Error, the wildcard switch name is empty."},
    {"id":"2064", "des_ch":"错误, 通配交换的端口组为空", "des_en":"Error, the portgroup of wildcard switch is empty."},
    {"id":"2065", "des_ch":"错误, 通配交换的端口组类型无效", "des_en":"Error, the portgroup type of wildcard switch is invalid.."},
    {"id":"2066", "des_ch":"错误, 通配交换的EVB模式无效", "des_en":"Error, the wildcard switch evbmode is invalid."},
    {"id":"2067", "des_ch":"错误, 通配交换已存在", "des_en":"Error, the wildcard switch is already exsit."},
    {"id":"2068", "des_ch":"错误, 通配交换查询数据库失败", "des_en":"Error, the wildcard switch get db failed."},
    {"id":"2069", "des_ch":"错误, 通配交换修改数据库失败", "des_en":"Error, the wildcard switch set db failed."},
	{"id":"2070", "des_ch":"错误, 通配交换没有网口", "des_en":"Error, the wildcard switch not exist port."},
	{"id":"2071", "des_ch":"错误, 通配交换参数无效", "des_en":"Error, the wildcard switch invalid param."},
	{"id":"2072", "des_ch":"错误, 通配虚拟口查询数据库失败", "des_en":"Error, the wildcard virtual port get db failed."},
	{"id":"2073", "des_ch":"错误, 通配虚拟口修改数据库失败", "des_en":"Error, the wildcard virtual port set db failed."},
	{"id":"2074", "des_ch":"错误, 通配虚拟口已存在", "des_en":"Error, the wildcard virtual port is exist."},
	{"id":"2075", "des_ch":"错误, 通配虚拟进口名字为空", "des_en":"Error, the wildcard virtual port name is empty."},
	{"id":"2076", "des_ch":"错误, 通配虚拟口操作码无效", "des_en":"Error, the wildcard virtual port opcode is invalid."},
	{"id":"2077", "des_ch":"错误, 通配虚拟口实例为空", "des_en":"Error, the wildcard virtual port instance is null."},
	{"id":"2078", "des_ch":"错误, 通配交换实例为空", "des_en":"Error, the wildcard switch instance is null."},
	{"id":"2079", "des_ch":"错误, 通配环回查询数据库失败", "des_en":"Error, the wildcard loop get db failed."},
	{"id":"2080", "des_ch":"错误, 通配环回修改数据库失败", "des_en":"Error, the wildcard loop set db failed."},
	{"id":"2081", "des_ch":"错误, 通配环回已存在", "des_en":"Error, the wildcard loop is exist."},
	{"id":"2082", "des_ch":"错误, 通配环回名字为空", "des_en":"Error, the wildcard loop name is empty."},
    {"id":"2083", "des_ch":"错误, 通配环回操作码无效骄", "des_en":"Error, the wildcard loop opcode is invalid."},
    {"id":"2084", "des_ch":"错误, 虚拟机迁移查询数据库失败", "des_en":"Error, vm migrate get db failed."},
    {"id":"2085", "des_ch":"错误, 虚拟机迁移修改数据库失败", "des_en":"Error, vm migrate set db failed."},
    {"id":"2086", "des_ch":"错误, 虚拟机迁移已存在", "des_en":"Error, vm migrate is exist."},
    {"id":"2087", "des_ch":"错误, 虚拟机迁移参数无效", "des_en":"Error, vm migrate param is invaild."},
    {"id":"2088", "des_ch":"错误, 虚拟机迁移DB不相同", "des_en":"Error, vm migrate input db not same."},
    {"id":"2089", "des_ch":"错误, 虚拟机迁移实例为空", "des_en":"Error, vm migrate instance is null."},
    {"id":"2091", "des_ch":"错误, uplink端口组MTU小于KERNEK端口组MTU", "des_en":"Error, wildcard uplink  portgroup MTU is less than kernel portgroup MTU."},
    {"id":"2092", "des_ch":"错误, uplink端口组冲突", "des_en":"Error, wildcard switch uplink portgroup is conflict."},
    {"id":"2093", "des_ch":"错误, 混用交换uplink端口组必须相同", "des_en":"Error, wildcard switch mix uplink portgroup must be the same."},
    {"id":"2094", "des_ch":"错误, 混用交换的UPLINK端口BOND模式必须相同", "des_en":"Error, wildcard switch mix uplink port bond mode must be the same."},
    {"id":"2100", "des_ch":"错误, VNA模块处于离线状态", "des_en":"Error,VNA agent module is offline."},
    {"id":"2101", "des_ch":"错误, VNA模块没有注册", "des_en":"Error,VNA agent module is not registered."},
    {"id":"2102", "des_ch":"错误, 删除失败", "des_en":"Error, VNA delete failed."},
    {"id":"2103", "des_ch":"错误, 删除数据库操作失败", "des_en":"Error,VNA delete database failed."},
    {"id":"2104", "des_ch":"错误, VNA模块处于在线状态", "des_en":"Error, VNA agent module is online."}, 
	{"id":"3000", "des_ch":"超时, 应答超时", "des_en":"TimeOut,Ack TimeOut"},
	{"id":"3001", "des_ch":"失败, 创建集群失败", "des_en":"Failed,Create Cluster Fail"},
	{"id":"3002", "des_ch":"失败, 集群已注册", "des_en":"Failed,Cluster have registerd"},
	{"id":"3003", "des_ch":"失败, 集群不存在", "des_en":"Failed,Cluster does not exist"},
	{"id":"3004", "des_ch":"失败, 集群未注册", "des_en":"Failed,Cluster does not register"},
	{"id":"3005", "des_ch":"失败, 集群资源未释放完毕", "des_en":"Failed,Cluster resource is using"},
	{"id":"4000", "des_ch":"失败, 文件不存在", "des_en":"Failed, file not exist"},
	{"id":"4001", "des_ch":"失败, 镜像已经注册", "des_en":"Failed, image have already registered"},
	{"id":"4002", "des_ch":"失败, 镜像正在被使用", "des_en":"Failed, image is using"},
	{"id":"4003", "des_ch":"失败, 无效查询类型", "des_en":"Failed, invalid query type"},
	{"id":"4004", "des_ch":"失败, 查询失败", "des_en":"Failed to query"},
    {"id":"4005", "des_ch":"操作进行中", "des_en":"operation is in progress"},
    {"id":"4006", "des_ch":"失败，镜像已被部署。如需删除，请先撤销部署", "des_en":"Failed, image is deployed"},
	{"id":"5000", "des_ch":"失败, 工程名冲突", "des_en":"Failed, project name conflict"},
	{"id":"5001", "des_ch":"失败, 工程存在虚拟机", "des_en":"Failed, project contain virtual machine"},
	{"id":"5002", "des_ch":"失败, 无效查询类型", "des_en":"Failed, invalid query type"},
	{"id":"6000", "des_ch":"失败, 无效查询类型", "des_en":"Failed, invalid query type"},
    {"id":"6001", "des_ch":"失败, 获取镜像失败", "des_en":"Failed to acquire image"},
    {"id":"6002", "des_ch":"失败, 模板名冲突", "des_en":"Failed, vmtemplate name conflict"},
    {"id":"6003", "des_ch":"模板发布失败，因为镜像未发布", "des_en":"Failed to publish vmtemplate because image is not public"},    
	{"id":"7000", "des_ch":"失败, 获取镜像失败", "des_en":"Failed to acquire image"},
	{"id":"7001", "des_ch":"失败, 无效的工程", "des_en":"Failed, invalid project"},
	{"id":"7002", "des_ch":"失败, 获取虚拟机模板失败", "des_en":"Failed to acquire vmtemplate"},
	{"id":"7003", "des_ch":"失败, 该操作当前状态被禁止", "des_en":"Failed, the operation is forbidden in current state"},
	{"id":"7004", "des_ch":"失败, 没有集群适合部署虚拟机", "des_en":"Failed, no cluster is suitable to the vm"},
	{"id":"7005", "des_ch":"失败, 在集群上操作虚拟机失败", "des_en":"Failed to action vm in cluster"},
	{"id":"7006", "des_ch":"失败, 在主机上操作虚拟机失败", "des_en":"Failed to action vm in host"},
	{"id":"7007", "des_ch":"失败, 无效查询类型", "des_en":"Failed, invalid query type"},
	{"id":"7008", "des_ch":"失败, 无效操作类型", "des_en":"Failed, invalid action type"},
	{"id":"7009", "des_ch":"失败, 虚拟机已部署禁止修改操作", "des_en":"Failed, modify is forbidden for VM has deployed"},
    {"id":"7013", "des_ch":"失败, 映像部署失败", "des_en":"Failed, deploy image failed"},
    {"id":"7014", "des_ch":"映像部署中", "des_en":"Image deployment"},
    {"id":"7015", "des_ch":"失败, 计算资源不足", "des_en":"Failed, no enough compute resource."},
	{"id":"7016", "des_ch":"失败, 共享存储资源不足", "des_en":"Failed, no enough share storagy resource."},
	{"id":"7017", "des_ch":"失败, 网络资源不足", "des_en":"Failed, no enough network resource."},
	{"id":"7018", "des_ch":"失败, TC分配网络资源失败", "des_en":"Failed, allocate network resource failes in TC."},
    {"id":"8000", "des_ch":"冲突, 用户名已存在", "des_en":"Conflict, user already exist."},
	{"id":"8001", "des_ch":"冲突, 用户组名已存在", "des_en":"Conflict, usergroup already exist."},
	{"id":"8002", "des_ch":"错误, 用户不存在", "des_en":"Error, user does not exist."},
	{"id":"8003", "des_ch":"错误, 用户组不存在", "des_en":"Error, usergroup does not exist."},
	{"id":"8004", "des_ch":"错误, 确认密码与密码不一致", "des_en":"Error, confirm password and password are inconsistent."},
	{"id":"8005", "des_ch":"错误, 默认用户不能禁用或删除", "des_en":"Error, the default user cannot be disabled or deleted."},
	{"id":"8006", "des_ch":"错误, 用户不能禁用或删除自己", "des_en":"Error, user cannot disable or delete his own account."},
	{"id":"8007", "des_ch":"错误, 默认用户必须是云管理员", "des_en":"Error, the default user must be a cloud administrator."},
	{"id":"8008", "des_ch":"错误, 组中还有用户", "des_en":"Error, There are users in the usergroup."},
	{"id":"8009", "des_ch":"错误, 用户有已部署的虚拟机", "des_en":"Error, The user has deployed vm."},
	{"id":"8010", "des_ch":"错误, 用户有上传的镜像, 请先删除", "des_en":"Error, The user has image, delete it first."},
	{"id":"10001", "des_ch":"失败, 通过UID查找用户失败", "des_en":"Failed, query user name by uid failed"},
    {"id":"10002", "des_ch":"失败, 无效查询类型", "des_en":"Failed, invalid query type"},
    {"id":"11000", "des_ch":"当前SNMP配置表不存在", "des_en":"The SNMP configuration database do not exist"},
    {"id":"11001", "des_ch":"查询数据库失败", "des_en":"Failed to query database"},
    {"id":"11002", "des_ch":"SNMP配置表新增失败", "des_en":"Failed to add a record to the SNMP configuration database"},
    {"id":"11003", "des_ch":"SNMP配置表更新失败", "des_en":"Failed to modify the SNMP configuration database"},
    {"id":"11004", "des_ch":"配置数据错误", "des_en":"Configuration value is wrong"},
    {"id":"11010", "des_ch":"获取session字符串失败", "des_en":"Get the session string failed"},
    {"id":"11011", "des_ch":"密码长度超过限制", "des_en":"The length of the password exceed the limitation"},
    {"id":"11020", "des_ch":"此记录已经存在", "des_en":"The record already exist"},
    {"id":"11021", "des_ch":"记录不存在", "des_en":"The record do not exist"},
    {"id":"11022", "des_ch":"记录删除失败", "des_en":"Delete the record failed"},
    {"id":"13001", "des_ch":"失败, SC未应答", "des_en":"Failed, sa controller is not answered"},
    {"id":"13002", "des_ch":"失败, SA不存在", "des_en":"Failed, sa not exist"},
    {"id":"13003", "des_ch":"失败, 更新SC数据库失败", "des_en":"Failed, update sc db err"},
    {"id":"13004", "des_ch":"失败, 删除SC数据库记录失败", "des_en":"Failed, delete sc db err"},
    {"id":"13005", "des_ch":"失败, 插入SC数据失败", "des_en":"Failed, insert sc db err"},    
    {"id":"13006", "des_ch":"失败, SA与集群映射关系已存在", "des_en":"Failed, map already exist"},      
    {"id":"13008", "des_ch":"失败, SA正在使用中，无法删除", "des_en":"Failed, sa is still using,can't remove"},    
    {"id":"web_err1", "des_ch":"正在修改中，请先提交！", "des_en":"Now in modify state, please submit first!"},
    {"id":"desc_too_long", "des_ch":"描述信息的长度不能大于128！", "des_en":"Description length can not be greater than 128!"},
    {"id":"no_operate_obj", "des_ch":"请选择一个操作对象！", "des_en":"Please select an operating object!"},
    {"id":"invalid_param", "des_ch":"无效的参数！", "des_en":"Invalid input data!"},
    {"id":"tcu_range_tip", "des_ch":"TCU输入范围1~128！", "des_en":"TCU input range is 1~128!"},
    {"id":"netplane_name_invalid", "des_ch":"网络平面名称必须由数字、字母或下划线组成，且不能为空！", "des_en":"Netplane must be composed of numbers, letters or an underscore, and can not be empty!"},
    {"id":"web_not_sirov", "des_ch":"非SIROV网口不能设置自环！", "des_en":"The port is not sriov!"},
    {"id":"web_last_updatetime", "des_ch":"最后一次更新于", "des_en":"last update time"},
    {"id":"no_jdk_tip", "des_ch":"系统检测到您的计算机没有安装JDK软件包(版本不能低于1.6)!", "des_en":"System detected that you do not have to install the JDK package(Version can not be lower than 1.6)!"},
    {"id":"download", "des_ch":"下载", "des_en":"Download"},
    {"id":"refresh", "des_ch":"刷新", "des_en":"Refresh"},
    {"id":"loadfailed_dbdriver", "des_ch":"加载数据库驱动失败!", "des_en":"Failed to load the database driver!"},
    {"id":"errinfo_loadfailed_dbdriver", "des_ch":"请检查数据库连接配置文件中驱动选项!", "des_en":"Please check database connection profile-driven options!"},
    {"id":"connectfailed_tcdb", "des_ch":"连接Tecs中心数据库失败!", "des_en":"Failed to connect TC database!"},
    {"id":"errinfo_connectfailed_tcdb", "des_ch":"1、请检查是否安装PHP包\n2、请检查数据库连接配置文件主机、端口、用户名、密码、数据库名等选项!", "des_en":"1.Check that you installed PHP packages\n2.Check the database connection configuration file to the host, port, username, password, database name options!"},
    {"id":"connectfailed_ccdb", "des_ch":"连接集群数据库失败!", "des_en":"Failed to connect CC database!"},
    {"id":"errinfo_connectfailed_ccdb", "des_ch":"请联系数据库管理员查看CC上报的数据库信息!", "des_en":"Contact the database administrator to view database information for the CC report!"},
    {"id":"failed_querydb", "des_ch":"查询数据库失败!", "des_en":"Failed to query the database!"},
    {"id":"noexist_record", "des_ch":"记录不存在!", "des_en":"The Record not exist!"},
    {"id":"vm_canceldeploy_image_error", "des_ch":"有镜像快照,撤销部署失败!", "des_en":"Image snapshot, cancel fails!"},
    {"id":"you_can_enter", "des_ch":"你还可以输入", "des_en":"You can also enter"},
    {"id":"count_charater", "des_ch":"个字符", "des_en":"Characters"},
    {"id":"no_distinguish_charater", "des_ch":"[不区分中英文]", "des_en":"[Not Case English and Chinese]"},
    {"id":"no_input_again", "des_ch":"不可再输入", "des_en":"Can no longer enter"},
    {"id":"confirm_op", "des_ch":"确认操作", "des_en":"confirm Opration"},
    {"id":"session_pwd_error", "des_ch":"密码错误,请重新输入", "des_en":"Wrong password, please re-enter"}
]