
/* This file is automatically generated by configure.  Do not modify by hand. */

/*
 * The defines found in net-snmp/agent/mib_module_config.h
 * are used to include/exclude header files referenced here.
 */

/*edit by anzhiqi*/
/*#include "mibII.h"*/
/*#include "ucd_snmp.h"*/
/*#include "snmpv3mibs.h"*/
/*#include "notification.h"*/
/*#include "target.h"*/
/*#include "agent_mibs.h"*/

#ifdef USING_AGENTX_MODULE
#include "agentx.h"
#endif

/*#include "agent_mibs.h"*/
/*#include "utilities.h"*/

#ifdef USING_HOST_MODULE
#include "host.h"
#endif

#ifdef USING_RMON_MODULE
#include "Rmon.h"
#endif

#ifdef USING_DISMAN_EVENT_MIB_MODULE
#include "disman/event-mib.h"
#endif

#ifdef USING_SMUX_MODULE
#include "smux.h"
#endif


#include "mibII/system_mib.h"
#include "mibII/sysORTable.h"

#ifdef HAVE_WIN32_PLATFORM_SDK
#include "mibII/at.h"
#include "mibII/interfaces.h"
#include "mibII/tcp.h"
#include "mibII/icmp.h"
#include "mibII/ip.h"
#include "mibII/udp.h"
#include "mibII/tcpTable.h"
#include "mibII/ipAddr.h"
#include "mibII/udpTable.h"
#include "mibII/var_route.h"
#endif

#include "mibII/snmp_mib.h"
#include "mibII/vacm_vars.h"
#include "mibII/setSerialNo.h"

#ifdef USING_UCD_SNMP_MODULE
#include "ucd-snmp/memory.h"
#include "ucd-snmp/vmstat.h"
#include "ucd-snmp/proc.h"
#include "ucd-snmp/versioninfo.h"
#include "ucd-snmp/pass.h"
#include "ucd-snmp/pass_persist.h"
#include "ucd-snmp/disk.h"
#include "ucd-snmp/loadave.h"
#include "ucd-snmp/extensible.h"
#include "agent/extend.h"
#include "ucd-snmp/errormib.h"
#include "ucd-snmp/file.h"
#include "ucd-snmp/dlmod.h"
#include "ucd-snmp/proxy.h"
#endif

#if HAVE_REGEX_H
#include "ucd-snmp/logmatch.h"
#endif

#include "snmpv3/snmpEngine.h"
#include "snmpv3/snmpMPDStats.h"
#include "snmpv3/usmStats.h"
#include "snmpv3/usmUser.h"
#include "notification/snmpNotifyTable.h"
#include "snmp-notification-mib/snmpNotifyFilterTable/snmpNotifyFilterTable.h"
#include "notification/snmpNotifyFilterProfileTable.h"
#include "target/snmpTargetAddrEntry.h"
#include "target/snmpTargetParamsEntry.h"
#include "target/target.h"
#include "target/target_counters.h"

/*edit by anzhiqi*/
/*#include "agent/nsTransactionTable.h"*/
/*#include "agent/nsModuleTable.h"*/
/*#include "agent/nsDebug.h"*/
/*#include "agent/nsCache.h"*/
/*#include "agent/nsLogging.h"*/
#include "utilities/override.h"

#ifdef USING_HOST_MODULE
#include "host/hr_system.h"
#include "host/hr_storage.h"
#include "host/hr_device.h"
#include "host/hr_other.h"
#include "host/hr_proc.h"
#include "host/hr_network.h"
#include "host/hr_print.h"
#include "host/hr_disk.h"
#include "host/hr_partition.h"
#include "host/hr_filesys.h"
#include "host/hr_swrun.h"
#include "host/hr_swinst.h"
#endif

#ifdef USING_RMON_MODULE
#include "Rmon/rows.h"
#include "Rmon/agutil.h"
#include "Rmon/statistics.h"
#include "Rmon/alarm.h"
#include "Rmon/history.h"
#include "Rmon/event.h"
#endif

#ifdef USING_DISMAN_EVENT_MIB_MODULE
#include "disman/mteTriggerTable.h"
#include "disman/mteTriggerDeltaTable.h"
#include "disman/mteTriggerExistenceTable.h"
#include "disman/mteTriggerBooleanTable.h"
#include "disman/mteTriggerThresholdTable.h"
#include "disman/mteObjectsTable.h"
#include "disman/mteEventTable.h"
#include "disman/mteEventNotificationTable.h"
#endif

#ifdef USING_SMUX_MODULE
#include "smux/smux.h"
#endif

#include "utilities/util_funcs.h"
#include "mibII/vacm_context.h"
#include "mibII/vacm_conf.h"
#include "utilities/execute.h"
#include "utilities/header_complex.h"

#ifdef USING_AGENTX_MODULE
#include "agentx/master.h"
#include "agentx/subagent.h"
#include "agentx/protocol.h"
#include "agentx/client.h"
#include "agentx/master_admin.h"
#include "agentx/agentx_config.h"
#endif

#ifdef USING_EXAMPLES_EXAMPLE_MODULE
#include "examples/example.h"
#endif

#ifdef USING_EXAMPLES_UCDDEMOPUBLIC_MODULE
#include "examples/ucdDemoPublic.h"
#endif

#ifdef USING_WINEXTDLL_MODULE
#include "winExtDLL.h"
#endif

